### ISSUE TITLE
error while running hic.experiment <- HiCDOC(hic.experiment)

### ISSUE THREAD

**Issue by schantalat** [mzytnicki/HiCDOC#8]
Hi,
I tried to run hicdoc on my own datasets and I got this error message  :
Clustering genomic positions.
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=07m 25s
Erreur dans vapply(validChromosomeNames, FUN = function(x) sort(object$condition[object@validAssay[[x]]])[1],  : 
  les valeurs doivent être de type 'character',
 mais FUN(X[[1]]) est de type 'double'
De plus : Il y a eu 12 avis (utilisez warnings() pour les visionner)

My files are in mcool format (I chose 160 kb resolution). I run 
Any thoughts about this error?
many thanks for your help

**Comment by emaigne** [comment]
Hi,

Sorry to hear that. Can you say what version of the package you used ? Also can you send me the output of 
- `warnings()`  I see that your code produces warnings()
- `yourobject@validAssay`, by replacing yourobject with the name of your object. 
 
Thanks

**Comment by schantalat** [comment]
Hello,
Unfortunately, I didn't save the outputs from warnings ()... I have to run again my notebook and I'll send you that.
thanks

**Comment by schantalat** [comment]
ok. The version is 1.5.0.

**Comment by schantalat** [comment]
I ran again the code and I got the following messages at this stage 

> hic.experiment <- detectCompartments(hic.experiment_filt6,kMeansDelta = 0.0001,kMeansIterations = 50,kMeansRestarts = 20)

Clustering genomic positions.
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=53s
Erreur dans vapply(validChromosomeNames, FUN = function(x) sort(object$condition[object@validAssay[[x]]])[1],  :
  les valeurs doivent être de type 'character',
 mais FUN(X[[1]]) est de type 'double'
> warnings()
Messages d'avis :
1: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  ... :
  pseudoinverse used at 3
2: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  ... :
  neighborhood radius 1
3: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  ... :
  reciprocal condition number  0
4: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  ... :
  There are other near singularities as well. 1
> hic.experiment_filt6
class: HiCDOCDataSet
dim: 2015519 4
metadata(0):
assays(1): ''
rownames: NULL
rowData names(1): chromosome
colnames: NULL
colData names(2): condition replicate
type: StrictGInteractions
regions: 9034
> hic.experiment_filt6@validAssay
$chr1
[1] 1 2 3 4

$chr2
[1] 1 2 3 4

$chr3
[1] 1 2 3 4

$chr4
[1] 1 2 3 4


Do you need something else ?
thanks for your help

**Comment by schantalat** [comment]
> hic.experiment_filt6$condition <- as.character(hic.experiment_filt6$condition)
> hic.experiment <- detectCompartments(hic.experiment_filt6,kMeansDelta = 0.0001,kMeansIterations = 50,kMeansRestarts = 20)
Clustering genomic positions.
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=01m 01s
Predicting A/B compartments.
Detecting significant differences.

It seems to work, 
thank you very much Elise :)

**Comment by emaigne** [comment]
Perfect. I close your issue and I will correct the code so the error can't happen again in next versions ! Thanks.
